# Generated by Django 3.1.7 on 2021-02-26 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32)),
                ('ipType', models.IntegerField()),
                ('rescanPriority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pluginEnabled', models.TextField()),
                ('skipPrivate', models.BooleanField()),
                ('timeout', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField()),
                ('lastRequest', models.DateTimeField()),
                ('currentConfig', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.config')),
            ],
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('createdAt', models.DateTimeField()),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.addr')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.worker')),
            ],
        ),
        migrations.CreateModel(
            name='LogEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64)),
                ('createdAt', models.DateTimeField()),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.addr')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.worker')),
            ],
        ),
    ]
