# Generated by Django 3.1.7 on 2021-05-08 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32, unique=True)),
                ('isPrivate', models.BooleanField(default=False)),
                ('rescanPriority', models.IntegerField(blank=True, default=0)),
                ('used', models.BooleanField(default=False)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pause', models.BooleanField(default=False)),
                ('skipPrivate', models.BooleanField(default=True)),
                ('timeout', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('modulesEnabled', models.ManyToManyField(to='modules.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('currentConfig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.config')),
            ],
        ),
    ]
