# Generated by Django 3.1.7 on 2021-03-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addr',
            name='rescanPriority',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
