# Generated by Django 3.1.7 on 2021-03-04 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddrEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64)),
                ('createdAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='addr',
            name='ipType',
        ),
        migrations.AlterField(
            model_name='config',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='LogEvent',
        ),
        migrations.AddField(
            model_name='addrevent',
            name='ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.addr'),
        ),
    ]
