# Generated by Django 3.1.7 on 2021-05-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addr',
            name='modules',
            field=models.ManyToManyField(blank=True, to='modules.Module'),
        ),
    ]
