# Generated by Django 3.2.5 on 2021-07-27 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
