# Generated by Django 3.1.7 on 2021-03-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210327_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addr',
            name='lastUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
