# Generated by Django 3.1.7 on 2021-04-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210327_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanresult',
            name='configVer',
        ),
        migrations.RemoveField(
            model_name='scanresult',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='scanresult',
            name='worker',
        ),
        migrations.AddField(
            model_name='addr',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='config',
            name='pause',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='config',
            name='skipPrivate',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='AddrEvent',
        ),
        migrations.DeleteModel(
            name='ScanResult',
        ),
    ]
