# Generated by Django 3.2.5 on 2021-08-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_worker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addr',
            old_name='isPrivate',
            new_name='is_private',
        ),
        migrations.RenameField(
            model_name='addr',
            old_name='lastUpdate',
            new_name='last_update',
        ),
        migrations.RenameField(
            model_name='addr',
            old_name='rescanPriority',
            new_name='scan_priority',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='modulesEnabled',
            new_name='modules_enabled',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='skipPrivate',
            new_name='skip_private',
        ),
    ]
