# Generated by Django 3.2.5 on 2021-08-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='availableAt',
            new_name='available_at',
        ),
    ]
