# Generated by Django 3.1.7 on 2021-05-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_created=True)),
                ('uuid', models.CharField(max_length=64)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
