# Generated by Django 3.1.7 on 2021-05-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
