# Generated by Django 3.2.5 on 2021-07-27 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_worker'),
        ('cluster', '0002_auto_20210517_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('currentConfig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.config')),
            ],
        ),
    ]
