# Generated by Django 3.2.5 on 2021-08-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0003_worker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='master',
            old_name='lastUpdate',
            new_name='last_update',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='currentConfig',
            new_name='current_config',
        ),
    ]
