name: Django develop check

on:
  workflow_dispatch:
  pull_request:
    branches: [ develop ]
    paths-ignore:
      - 'docs/**'

jobs:
  code-check:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: please
          POSTGRES_PASSWORD: change_me
          POSTGRES_DB: TouDoum
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Check Python version
        run: python --version

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run Make Migrations
        run: python manage.py makemigrations

      - name: Run Migrations
        run: python manage.py migrate

      - name: Run Test
        run: python manage.py test